dependencies:
  - python==3.11.7
  - pip==24.0
  - matplotlib==3.8.3
  - torch==2.2.1
  - torchvision==0.17.1
  - pip:
    - numpy==1.24.3
    - opencv-python==4.9.0.80
    - cvzone==1.4.1
    - mediapipe==0.10.10
    - tensorflow==2.16.1
    - tensorflow-hub==0.16.1
    - GitPython==3.1.43
    - gitdb==4.0.11
    - tensorboard==2.16.2

## Citation

```
@misc{Gordić2020nst-fast,
  author = {Gordić, Aleksa},
  title = {pytorch-nst-feedforward},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/gordicaleksa/pytorch-nst-feedforward}},
}
```

## Licence

[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)]
(https://github.com/gordicaleksa/pytorch-nst-feedforward/blob/master/LICENCE)